# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2908565ddc8ee2af959336b7ef17b678a124578764f158b0887178aa4ce5c4771e45207b22ee3e2ba38f83ae1cb3f2b74bfa4fb39b8867801f2d2cecfcbcf1f7

test:
  secret_key_base: 568ec54436ea266e1bd6291a79678a400f1877cdc855326b46c2789f348dd84d0f23a2e01416e4ef36d69ec953393f77a5639eea7aab913c58cde64f4abaeaa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
